
move_group_name: "manipulator"

table_position  :  {x: 0, y: 0, z: -0.015} # 0.015 is hight of UR5e base plate
table_scale  :  {x: 0.9, y: 1.5, z: 0.1}

mortar_top_position  :  {x:  0, y: 0.3, z: 0.1} 
mortar_inner_scale:  {x:  0.04, y: 0.04, z: 0.035} # official infomation says 0.04 * 0.04 * 0.032 but z is more deep actually 

funnel_position  :  {x:  0.0, y: -0.5, z: 0}
funnel_scale  :  {x:  0.015, y: 0.015, z: 0.15}
