/**:
  ros__parameters:
    experimental_time : 90.0

    # end effector params
    grinding_eef_link: "pestle_tip"
    gathering_eef_link: "spatula_tip"

    # ik and motion planner params 
    urdf_name: "ur5e" # support "ur3e" and "ur5e"
    ik_solver: "trac_ik" # only "trac_ik" is supported, "ikfast" will be supported in the future
    motion_planner_id: "TRRT" # recommended "TRRT"(highly optimal but long planning time) or "RRTConnect" (low optimal but fast planning)
    planning_time : 20.0 # timeout for motion planning

    # grinding params
    grinding_pos_beginning : 
      - -8.0
      - 0.0
    grinding_pos_end :
      - -8.0
      - 0.0001
    grinding_center_pos:
      - 0.0
      - 0.0
    grinding_number_of_rotation : 10.0
    grinding_sec_per_rotation : 0.5 # 0.5 >
    grinding_angle_param : 0.3 #0 - 0.3
    grinding_rz_beginning : 35.0
    grinding_rz_end : 35.0
    grinding_vel_scale : 1.0
    grinding_acc_scale : 1.0
    grinding_number_of_waypoints_per_circle : 100.0
    grinding_yaw_bias : 0.0
    grinding_total_joint_diffence_for_planning : 10.0

    # circular gathering params 
    gathering_pos_beginning : 
      - -30.0
      - 0.0
    gathering_pos_end :
      - -18.0
      - 0.0001
    gathering_number_of_rotation : 8.0
    gathering_sec_per_rotation : 2.0
    gathering_angle_param : 0.0
    gathering_rz_beginning : 31.3
    gathering_rz_end : 31.3
    gathering_vel_scale : 0.1
    gathering_acc_scale : 0.1
    gathering_number_of_waypoints_per_circle : 20.0
    gathering_yaw_bias : 0.0
    gathering_total_joint_diffence_for_planning : 20.0



    pouring_hight_at_funnel : 0.2

    # sound param
    sound_RMS_threshold : 0.03