version: "3.8"

################################################################################

services:
  humble:
    hostname: onolab
    runtime: ${DOCKER_RUNTIME}
    privileged: true
    network_mode: host # Use host network(IP and ports).
    environment:
      # Pass host user information.
      - HOST_USER=${USER}
      - HOST_UID=1000
      - HOST_GID=1000
      # Display X Server GUI.
      - DISPLAY
      - QT_X11_NO_MITSHM=1
      # Set ROS environment variables. It is instead of writing them in .bashrc.
      - ROS_DOMAIN_ID=1
      - ROS_VERSION=2
      - ROS_PYTHON_VERSION=3
      - ROS_DISTRO=humble
      - ROS_LOCALHOST_ONLY=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

    image: onolab_ros2_humble
    build:
      dockerfile: ./Dockerfile
    volumes:
      # Map ROS workspace folders.
      - ../:/home/ubuntu/onolab/
      # Grant display access to X Server.
      - /tmp/.X11-unix:/tmp/.X11-unix
      # Grant access to usb ports
      - /dev/:/dev/
    tty: true
