grinding_demo_node:
  ros__parameters:
    # IK Solver Parameters
    trac_ik_solver_type: "Distance"
    trac_ik_timeout: 0.005
    trac_ik_epsilon: 1e-5

    # Robot and Controller Parameters
    controller_name: "scaled_joint_trajectory_controller"
    joint_names: [
      "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint",
      "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"
    ]
    base_link: "base_link"
    grinding_ee_link: "pestle_tip"
    gathering_ee_link: "spatula_tip"
    robot_description_package: "grinding_robot_description"
    robot_description_file_path: "/urdf/ur/ur5e_with_pestle.urdf"
    ik_solver: "trac_ik"

    # Grinding Parameters (positions in mm, will be converted to meters internally)
    grinding_pos_beginning_mm: [-8.0, 0.0]
    grinding_pos_end_mm: [-8.0, 0.0001]
    grinding_center_pos_mm: [0.0, 0.0]
    grinding_rz_beginning_mm: 35.0
    grinding_rz_end_mm: 35.0
    grinding_number_of_rotation: 5.0
    grinding_angle_scale: 0.3
    grinding_yaw_bias: 3.1415926535
    grinding_number_of_waypoints_per_circle: 100
    grinding_sec_per_rotation: 1.0
    grinding_joint_difference_limit_for_motion_planning: 0.03

    # Gathering Parameters (positions in mm, will be converted to meters internally)
    gathering_pos_beginning_mm: [30.0, 0.0]
    gathering_pos_end_mm: [-22.0, 0.0001]
    gathering_center_pos_mm: [0.0, 0.0]
    gathering_rz_beginning_mm: 35.0
    gathering_rz_end_mm: 35.0
    gathering_number_of_rotation: 5.0
    gathering_angle_scale: 0.0
    gathering_yaw_bias: 3.1415926535
    gathering_number_of_waypoints_per_circle: 100
    gathering_sec_per_rotation: 2.0
    gathering_joint_difference_limit_for_motion_planning: 0.03

    # Additional parameters
    motion_planner_id: "TRRT"
    planning_time: 20.0
    max_attempts: 5

    # Motion Execution Parameters
    motion:
      joint_difference_limit_rad: 0.03
      max_ik_retries_on_jump: 100
      ik_retry_perturbation_rad: 0.05
      pre_motion: true
      post_motion: true
      wait_for_completion: true
