grinding_demo_node:
  ros__parameters:
    # IK Solver Parameters
    trac_ik_solver_type: "Distance"
    trac_ik_timeout: 0.005
    trac_ik_epsilon: 1e-5

    # Robot and Controller Parameters
    controller_name: "scaled_joint_trajectory_controller"
    joint_names: [
      "shoulder_pan_joint", "shoulder_lift_joint", "elbow_joint",
      "wrist_1_joint", "wrist_2_joint", "wrist_3_joint"
    ]
    base_link: "base_link"
    grinding_ee_link: "pestle_tip"
    gathering_ee_link: "spatula_tip"
    robot_description_package: "grinding_robot_description"
    robot_description_file_path: "/urdf/ur/ur5e_with_pestle.urdf"
    ik_solver: "trac_ik"


    # Mortar Parameters
    mortar:
      inner_size:
        x: 0.04
        y: 0.04
        z: 0.035
      top_position:
        x: -0.2    # Updated from grinding demo snippet
        y: 0.4     # Updated from grinding demo snippet
        z: 0.3     # Updated from grinding demo snippet

    # Initial Pose Parameters
    init_pose:
      offset_z: 0.05
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0

    # Grinding Parameters
    grinding:
      depth_st_mm: -35.0
      depth_end_mm: -35.0
      start_pos_xy_mm:
        - -8.0
        - 0.0
      end_pos_xy_mm:
        - -8.0
        - 0.0001
      center_offset_mm: # Matches input grinding_center_pos: [0, 0]
        x: 0.0
        y: 0.0
      rotations: 5.0
      angle_scale: 0.3
      yaw_twist_per_rotation_deg: 0.0 # Matches snippet's np.pi / 2
      waypoints_per_circle: 100
      sec_per_rotation: 1.0
      vel_scale: 1.0
      acc_scale: 1.0
      yaw_bias_rad: 3.1415926535

    # Gathering Parameters
    gathering:
      depth_st_mm: -35.0
      depth_end_mm: -35.0
      start_pos_xy_mm:
        - 30.0
        - 0.0
      end_pos_xy_mm:
        - -22.0
        - 0.0001
      center_offset_mm:
        x: 0.0
        y: 0.0
      rotations: 5.0
      angle_scale: 0.0
      waypoints_per_circle: 100
      sec_per_rotation: 2.0
      vel_scale: 0.1
      acc_scale: 0.1
      yaw_bias_rad: 3.1415926535

    # Motion Execution Parameters
    motion:
      joint_difference_limit_rad: 0.03
      max_ik_retries_on_jump: 100
      ik_retry_perturbation_rad: 0.05
      pre_motion: true
      post_motion: true
      wait_for_completion: true
